WebApplication4/Models/Notification.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication4.Models
{
    public class Notification
    {
        public int Id { get; set; }
        public Guid UserId { get; set; }
        public string NotificationTitle { get; set; }
        public string NotificationIcon { get; set; }
        public string EntityId { get; set; }
        public string NotificationMessage { get; set; }
        public string Link { get; set; }
        public bool IsRequest { get; set; }
        public DateTime NotificationTime { get; set; }
        public bool Seen { get; set; }
    }
}

WebApplication4/ViewModels/NotificationsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebApplication4.Models;

namespace WebApplication4.ViewModels
{
    public class NotificationsViewModel
    {
        public List<Notification> Notifications { get; set; }
        public Int16 NotificationCount { get; set; }
    }
}

WebApplication4/Controllers/NotificationController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Services;
using WebApplication4.SignalIR;

namespace WebApplication4.Controllers
{
    public class NotificationController : Controller
    {
        private readonly NotificationService  _notificationService= new NotificationService();
        private readonly UserProfileService  _userProfileService= new UserProfileService();
        
        [Route("notifications/", Name = "notifications")]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var currentUserProfile = _userProfileService.GetUserProfileByUserId(new Guid(userId));
            var notifications = _notificationService.GetAllNotifications(currentUserProfile.Id);
            return View(notifications);
        }

        [Route("notifications/delete", Name = "notification-delete")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Delete(Int16 notificationId)
        {
            _notificationService.DeleteNotification(notificationId);
            return Json(new { Message = "notification_deleted" });
        }
        [Route("notifications/delete-all", Name = "notification-delete-all")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteAll(Guid userProfileId)
        {
            _notificationService.DeleteAllNotifications(userProfileId);
            return Json(new { Message = "all_notification_deleted" });
        }
    }
}

WebApplication4/Views/Notification/Index.cshtml
@model IEnumerable<WebApplication4.Models.Notification>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
@using (Html.BeginForm("DeleteAll", "Notification", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <p>
        @Html.ActionLink("Delete All Notifications", "DeleteAll")
    </p>
}
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NotificationTitle)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.NotificationMessage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Link)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NotificationTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Seen)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NotificationTitle)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.NotificationMessage)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Link)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NotificationTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Seen)
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>